### ISSUE TITLE
Documentation Site Is Down

### ISSUE THREAD

**Issue by SoundsSerious** [RecallGraph/RecallGraph#27]
Hi,

very interested in learning more about your framework, however the documentation link is down https://docs.recallgraph.tech/

Also it seems the example link is out of date too.

**Comment by adityamukho** [comment]
Hi,
RecallGraph hasn't been updated in over 3 years, and is currently not under active maintenance. However, if you still wish to try pairing it with an old enough version of ArangoDB (3.6) and try your luck, you can access the documentation site here: https://adityamukho.gitbook.io/recallgraph-docs.

If you face any other issues, feel free to open a new ticket. Marking this as closed.
